---
- name: check if lib that needs to be manually removed is installed
  command: rpm -q {{ mysql_remove_lib }}
  register: mysql_rpm_check
  when: mysql_remove_lib is defined and mysql_remove_lib != ''
  changed_when: false
  failed_when: mysql_rpm_check.rc > 1
  tags:
    - mysql
    - packages

- name: manually remove package with nodeps so we can install new libs
  command: "rpm -e --nodeps {{ mysql_remove_lib }}"
  when: mysql_rpm_check is defined and mysql_rpm_check.rc == 0
  tags:
    - mysql
    - packages

- name: install mysql libs rpms
  yum: name={{ item }} state=present
  with_items: mysql_libs_rpms
  tags:
    - mysql
    - packages

- name: install mysqldb
  yum: name=MySQL-python state=present