---
- name: install mysql-connector-python
  yum: name=mysql-connector-python state=present
  when: mysql_flavor == 'mysql-community'
  tags:
    - mysql
    - packages

- name: check if lib that needs to be manually removed is installed
  command: rpm -q {{ mysql_remove_lib }}
  register: mysql_rpm_check
  when: mysql_remove_lib is defined and mysql_remove_lib != ''
  changed_when: false
  failed_when: mysql_rpm_check.rc > 1
  tags:
    - mysql
    - packages

- name: manually remove package with nodeps so we can install new libs
  command: "rpm -e --nodeps {{ mysql_remove_lib }}"
  when: mysql_remove_lib is defined and mysql_remove_lib != '' and mysql_rpm_check is defined and mysql_rpm_check.rc == 0
  tags:
    - mysql
    - packages

- name: install mysql libs rpms
  yum: name='{{ mysql_libs_rpms }}' state=present
  tags:
    - mysql
    - packages

- name: install mysqldb
  yum: name=MySQL-python state=present
  when: ansible_distribution_major_version|int < 8

- name: install PyMySQL
  yum:
    name: python3-PyMySQL
    state: present
  when: ansible_distribution_major_version|int > 7
