---
- name: install mysql libs rpms
  yum: name={{ item }} state=present
  with_items: mysql_libs_rpms
  tags:
    - mysql
    - packages

- name: install mysqldb
  yum: name=MySQL-python state=present